[package]
name = "code-skill-rater"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
